// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://kxhdpijlaefxrthofjsf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4aGRwaWpsYWVmeHJ0aG9manNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjA1MDQsImV4cCI6MjA2Nzg5NjUwNH0.cEFBUzuUUvBm75Et6SUYjNJZUEb2Dl04k1TWne-ZsqE';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// New Supabase client for the different project
const NEW_SUPABASE_URL = import.meta.env.VITE_NEW_SUPABASE_URL;
const NEW_SUPABASE_ANON_KEY = import.meta.env.VITE_NEW_SUPABASE_ANON_KEY;

export const newSupabase = createClient(NEW_SUPABASE_URL, NEW_SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

