// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxhdpijlaefxrthofjsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4aGRwaWpsYWVmeHJ0aG9manNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjA1MDQsImV4cCI6MjA2Nzg5NjUwNH0.cEFBUzuUUvBm75Et6SUYjNJZUEb2Dl04k1TWne-ZsqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});